on:
  # Runs on any commit landed in main, whether direct push or a merged PR
  push:
    branches:
      - main

  # (Optional) Runs on PR events _against_ main
  pull_request:
    branches:
      - main
jobs:
  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-go@v3
  #       with:
  #         go-version: 1.19
  #     - uses: golangci/golangci-lint-action@v3
  test:
    runs-on: ubuntu-latest
    #needs: lint
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - run: go test -v ./...
  release:
    environment: prod
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: go-semantic-release/action@v1
        with:
          hooks: goreleaser
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
